FROM node:latest

LABEL "com.github.actions.name"="test"
LABEL "com.github.actions.description"=""
LABEL "com.github.actions.icon"="code"
LABEL "com.github.actions.color"="green"

CMD yarn --silent test
