name: ci
on: [push, pull_request]

jobs:
  fmt:
    runs-on: ubuntu-latest
    container: node
    steps:
      - uses: actions/checkout@v1
      - run: yarn --frozen-lockfile && yarn fmt
        env:
          CI: 1

  lint:
    runs-on: ubuntu-latest
    container: node
    steps:
      - uses: actions/checkout@v1
      - run: yarn --frozen-lockfile && yarn lint
        env:
          CI: 1

  test:
    runs-on: ubuntu-latest
    container: node
    steps:
      - uses: actions/checkout@v1
      - run: yarn --frozen-lockfile && yarn test
        env:
          CI: 1
